name: Auto-update main branch

on:
  push:
    branches:
      - main

jobs:
  update-main-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/Project-Digital-Citizen/Front-End.git
        git fetch upstream

    - name: Merge changes into main
      run: |
         git checkout main
         git merge --allow-unrelated-histories upstream/main

    - name: Push changes
      run: |
        git push origin main
