name: Update Main Branch

on:
  push:
    branches:
      - main  # Ganti 'main' dengan nama branch utama Anda jika berbeda

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/Project-Digital-Citizen/Front-End.git
        git fetch upstream

    - name: Update Main Branch
      run: |
        git checkout main
        git merge upstream/main
        git push origin main
