name: Auto Update Main Branch

on:
  push:
    branches:
      - main

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Upstream Remote
      run: git remote add upstream https://github.com/Project-Digital-Citizen/Front-End.git

    - name: Fetch Upstream Changes
      run: git fetch upstream main

    - name: Merge Upstream Changes into Main
      run: git merge --allow-unrelated-histories upstream/main

    - name: Push Changes to Fork
      run: git push origin main
